In [58]:
from bs4 import BeautifulSoup as bs
from splinter import Browser
import pandas as pd
import os
import time
import requests
import warnings
warnings.filterwarnings('ignore')

In [59]:
def init_browser():
     executable_path = {"executable_path": "/usr/local/bin/chromedriver"}
     return Browser("chrome", **executable_path, headless=False)

In [63]:
url_nfl = "https://www.pro-football-reference.com/years/2006/draft.htm"

nfl_player_table = pd.read_html(url_nfl, skiprows=0)[0]
nfl_player_table

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Rnd               Pick                 Tm
0                    1                  1                HOU
1                    1                  2                NOR
2                    1                  3                TEN
3                    1                  4                NYJ
4                    1                  5                GNB
..                 ...                ...                ...
256                  7                251                HOU
257                  7                252                NOR
258                  7                253                GNB
259                  7                254                SFO
260                  7                255                OAK

        Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                    Player                Pos                Age
0           Mario Williams                 DE                 21
1              Reggie Bush                 RB                 21
2              Vince Young                 QB                 23
3    D'Brickashaw Ferguson                  T                 22
4                A.J. Hawk                 LB                 22
..                     ...                ...                ...
256         David Anderson                 WR                 23
257        Marques Colston                 WR                 23
258         Dave Tollefson                 DE                 24
259         Vickiel Vaughn                 DB                NaN
260          Kevin McMahan                 WR                NaN

    Unnamed: 6_level_0 Misc    Unnamed: 9_level_0  ... Rushing      Receiving  \
                    To  AP1 PB                 St  ...     Yds   TD       Rec
0                 2016    1  4                  9  ...       0    0         0
1                 2016    0  0                  8  ...    5490   36       477
2                 2011    0  2                  4  ...    1459   12         0
3                 2015    0  3                 10  ...       0    0         0
4                 2016    0  0                 10  ...       0    0         0
..                 ...  ... ..                ...  ...     ...  ...       ...
256               2011    0  0                  0  ...       0    0        88
257               2015    0  0                  7  ...       7    0       711
258               2012    0  0                  0  ...       0    0         0
259                NaN    0  0                  0  ...     NaN  NaN       NaN
260                NaN    0  0                  0  ...     NaN  NaN       NaN

               Unnamed: 24_level_0 Unnamed: 25_level_0 Unnamed: 26_level_0  \
      Yds   TD                Solo                 Int                  Sk
0       0    0                 317                 NaN                97.5
1    3598   18                 NaN                 NaN                 NaN
2       0    0                 NaN                 NaN                 NaN
3       0    0                 NaN                 NaN                 NaN
4       0    0                 645                   9                20.0
..    ...  ...                 ...                 ...                 ...
256   965    4                   8                 NaN                 NaN
257  9759   72                   1                 NaN                 NaN
258     0    0                  62                 NaN                10.5
259   NaN  NaN                 NaN                 NaN                 NaN
260   NaN  NaN                 NaN                 NaN                 NaN

    Unnamed: 27_level_0 Unnamed: 28_level_0
           College/Univ Unnamed: 28_level_1
0    North Carolina St.       College Stats
1                   USC       College Stats
2                 Texas       College Stats
3              Virginia                 NaN
4              Ohio St.       College Stats
..                  ...                 ...
256        Colorado St.       College Stats
257             Hofstra                 NaN
258     NW Missouri St.                 NaN
259            Arkansas       College Stats
260               Maine                 NaN

[261 rows x 29 columns]

In [65]:
nfl_player_table.columns = ["Round", "Pick", "Team", "Player", "Position", "Age", "Until", "AP1", "PB", "YearsStarter", "CareerAverage", "DraftAverage", "Games", "PassComp", "PassAtt", "PassYards", "PassTDs", "Int", "RushAtt", "RushYards", "RushTDs", "Rec", "RecYards", "RecTDs", "TackleSolo", "DefInt", "Sacks", "College", "CollegeLink"]
nfl_player_table

,Round,Pick,Team,Player,Position,Age,Until,AP1,PB,YearsStarter,...,RushYards,RushTDs,Rec,RecYards,RecTDs,TackleSolo,DefInt,Sacks,College,CollegeLink
0,1,1,HOU,Mario Williams,DE,21,2016,1,4,9,...,0,0,0,0,0,317,NaN,97.5,North Carolina St.,College Stats
1,1,2,NOR,Reggie Bush,RB,21,2016,0,0,8,...,5490,36,477,3598,18,NaN,NaN,NaN,USC,College Stats
2,1,3,TEN,Vince Young,QB,23,2011,0,2,4,...,1459,12,0,0,0,NaN,NaN,NaN,Texas,College Stats
3,1,4,NYJ,D'Brickashaw Ferguson,T,22,2015,0,3,10,...,0,0,0,0,0,NaN,NaN,NaN,Virginia,NaN
4,1,5,GNB,A.J. Hawk,LB,22,2016,0,0,10,...,0,0,0,0,0,645,9,20.0,Ohio St.,College Stats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,7,251,HOU,David Anderson,WR,23,2011,0,0,0,...,0,0,88,965,4,8,NaN,NaN,Colorado St.,College Stats
257,7,252,NOR,Marques Colston,WR,23,2015,0,0,7,...,7,0,711,9759,72,1,NaN,NaN,Hofstra,NaN
258,7,253,GNB,Dave Tollefson,DE,24,2012,0,0,0,...,0,0,0,0,0,62,NaN,10.5,NW Missouri St.,NaN
259,7,254,SFO,Vickiel Vaughn,DB,NaN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arkansas,College Stats
260,7,255,OAK,Kevin McMahan,WR,NaN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maine,NaN

In [66]:
nfl_player_table.drop(nfl_player_table[ nfl_player_table["Player"] == "Player" ].index , inplace=True)
nfl_player_table.to_csv("nfl_2006_cleaned.csv")
nfl_player_table

,Round,Pick,Team,Player,Position,Age,Until,AP1,PB,YearsStarter,...,RushYards,RushTDs,Rec,RecYards,RecTDs,TackleSolo,DefInt,Sacks,College,CollegeLink
0,1,1,HOU,Mario Williams,DE,21,2016,1,4,9,...,0,0,0,0,0,317,NaN,97.5,North Carolina St.,College Stats
1,1,2,NOR,Reggie Bush,RB,21,2016,0,0,8,...,5490,36,477,3598,18,NaN,NaN,NaN,USC,College Stats
2,1,3,TEN,Vince Young,QB,23,2011,0,2,4,...,1459,12,0,0,0,NaN,NaN,NaN,Texas,College Stats
3,1,4,NYJ,D'Brickashaw Ferguson,T,22,2015,0,3,10,...,0,0,0,0,0,NaN,NaN,NaN,Virginia,NaN
4,1,5,GNB,A.J. Hawk,LB,22,2016,0,0,10,...,0,0,0,0,0,645,9,20.0,Ohio St.,College Stats
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,7,251,HOU,David Anderson,WR,23,2011,0,0,0,...,0,0,88,965,4,8,NaN,NaN,Colorado St.,College Stats
257,7,252,NOR,Marques Colston,WR,23,2015,0,0,7,...,7,0,711,9759,72,1,NaN,NaN,Hofstra,NaN
258,7,253,GNB,Dave Tollefson,DE,24,2012,0,0,0,...,0,0,0,0,0,62,NaN,10.5,NW Missouri St.,NaN
259,7,254,SFO,Vickiel Vaughn,DB,NaN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arkansas,College Stats
260,7,255,OAK,Kevin McMahan,WR,NaN,NaN,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maine,NaN

In [75]:
player = nfl_player_table["Player"]
player

KeyError: 'Player'

In [44]:
new = name["Player"].str.split(" ", n = 1, expand = True) 
  
# making separate first name column from new data frame 
name["First Name"]= new[0] 
  
# making separate last name column from new data frame 
name["Last Name"]= new[1] 
  
# Dropping old Name columns 
#data.drop(columns =["Name"], inplace = True) 
  
# df display 
new

                0          1
0           Mario   Williams
1          Reggie       Bush
2           Vince      Young
3    D'Brickashaw   Ferguson
4            A.J.       Hawk
..            ...        ...
256         David   Anderson
257       Marques    Colston
258          Dave  Tollefson
259       Vickiel     Vaughn
260         Kevin    McMahan

[255 rows x 2 columns]

In [38]:
pre_url = "https://www.sports-reference.com/cfb/players/"
post_url = "-1.html"
x = 0
first = new[0][x].lower()
last = new[1][x].lower()
full_url = f'{pre_url}{first}-{last}{post_url}'
college = pd.read_html(full_url, skiprows=0)[0]
college

  Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Year                School               Conf
0              *2005  North Carolina State                ACC
1             Career  North Carolina State                NaN

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Tackles          \
               Class                Pos                  G    Solo Ast Tot
0                 JR                 DL               12.0      32  30  62
1                NaN                NaN                NaN      32  30  62

              Def Int                 Fumbles
   Loss    Sk     Int Yds Avg  TD  PD      FR Yds  TD  FF
0  24.0  14.5     NaN NaN NaN NaN NaN     NaN NaN NaN NaN
1  24.0  14.5     NaN NaN NaN NaN NaN     NaN NaN NaN NaN

In [39]:
x = 0

for _ in nfl_player_table:
    try:
        pre_url = "https://www.sports-reference.com/cfb/players/"
        post_url = "-1.html"
        x = 0
        first = new[0][x].lower()
        last = new[1][x].lower()
        full_url = f'{pre_url}{first}-{last}{post_url}'
    
        if df.Position[x] == 'QB':
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'passCmp', 'passAtt', 'passPct', 'passYds', 'passY/A', 'passAY/A', 'passTD', 'passInt', 'passRate']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            df_player = df_player.set_index(df_player.Player)
            pd.merge(df_player, college_stats)
        
        elif df.Position[x] == 'RB':
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'recRec', 'recYds', 'recAvg', 'recTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            pd.merge(df_player, college_stats)
            
        elif df.Position[x] == 'WR':
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'recRec', 'recYds', 'recAvg', 'recTD', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            pd.merge(df_player, college_stats)
        
        elif df.Position[x] == 'TE':
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'recRec', 'recYds', 'recAvg', 'recTD', 'rushAtt', 'rushYds', 'rushAvg', 'rushTD', 'scrPlays', 'scrYds', 'scrAvg', 'scrTD']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            pd.merge(df_player, college_stats)
        
        elif df.Position[x] == 'K':
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts', 'Punts', 'puntYds', 'puntAvg']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            pd.merge(df_player, college_stats)
        
        elif df.Position[x] == 'P':
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'Punts', 'puntYds', 'puntAvg', 'XPM', 'XPA', 'XP%', 'FGM', 'FGA', 'FG%', 'Pts']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            pd.merge(df_player, college_stats)
    
        else:
            df_player = pd.read_html(full_url, skiprows=0)[0]
            df_player.columns = ['Player', 'School', 'Conf', 'Class', 'Pos', 'G', 'tackleSolo', 'tackleAst', 'tackleTot', 'tackleLoss', 'Sk', 'defInt', 'defYds', 'defAvg', 'defIntTD', 'defIntPD', 'fumFR', 'fumYds', 'fumTD', 'fumFF']
            df_player = df_player[df_player.Player == 'Career']
            df_player = df_player.reset_index(drop=True)
            df_player.iloc[0,0] = df.Player[x]
            df_player.drop(df_player.columns[[1,2,3,4,5]], axis=1, inplace = True)
            pd.merge(df_player, college_stats)
        
    except:
        pass
        x = x + 1
        print('Bagel, Dave?')

        
college_stats

Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?
Bagel, Dave?

NameError: name 'college_stats' is not defined